/* Generated by Pyrex 0.9.3.1 on Fri Jan  4 16:01:58 2008 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "stdlib.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "\nPyrex extension classes used by `seqmapping.py`.\n";

/* Declarations from _seqmapping */

staticforward PyTypeObject __pyx_type_11_seqmapping_CharToIntArrayMapping;

struct __pyx_obj_11_seqmapping_CharToIntArrayMapping {
  PyObject_HEAD
  int (table[256]);
  int out_size;
  PyObject *reverse_table;
};

staticforward PyTypeObject __pyx_type_11_seqmapping_IntToIntMapping;

struct __pyx_obj_11_seqmapping_IntToIntMapping {
  PyObject_HEAD
  int (*table);
  int in_size;
  int out_size;
};

static PyTypeObject *__pyx_ptype_11_seqmapping_CharToIntArrayMapping = 0;
static PyTypeObject *__pyx_ptype_11_seqmapping_IntToIntMapping = 0;

/* Implementation of _seqmapping */


static PyObject *__pyx_n_zeros;
static PyObject *__pyx_n_floor;
static PyObject *__pyx_n_random;
static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_Numeric;
static PyObject *__pyx_n_math;

static int __pyx_f_11_seqmapping_21CharToIntArrayMapping___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_21CharToIntArrayMapping___new__[] = "Init empty mapping (all characters map to -1)";
static int __pyx_f_11_seqmapping_21CharToIntArrayMapping___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  int __pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":29 */
  for (__pyx_v_i = 0; __pyx_v_i < 256; ++__pyx_v_i) {
    (((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->table[__pyx_v_i]) = (-1);
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":30 */
  ((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_dict;

static int __pyx_f_11_seqmapping_21CharToIntArrayMapping___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_11_seqmapping_21CharToIntArrayMapping___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":33 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_dict); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->reverse_table);
  ((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->reverse_table = __pyx_3;
  __pyx_3 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_chr;

static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_set_mapping(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_21CharToIntArrayMapping_set_mapping[] = "Modify mapping so \'chars\' map to \'symbol\'";
static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_set_mapping(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char __pyx_v_char;
  int __pyx_v_symbol;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"char","symbol",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ci", __pyx_argnames, &__pyx_v_char, &__pyx_v_symbol)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":37 */
  (((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->table[__pyx_v_char]) = __pyx_v_symbol;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":38 */
  __pyx_1 = (((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size <= __pyx_v_symbol);
  if (__pyx_1) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":39 */
    ((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size = (__pyx_v_symbol + 1);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":40 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_chr); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_char); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyInt_FromLong(__pyx_v_symbol); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  if (PyObject_SetItem(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->reverse_table, __pyx_2, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.set_mapping");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_i;


static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_21CharToIntArrayMapping_translate[] = "Translate \'string\' and return as int array";
static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_string = 0;
  int __pyx_v_s_len;
  int __pyx_v_t_len;
  unsigned char (*__pyx_v_s_buf);
  int (*__pyx_v_t_buf);
  PyObject *__pyx_v_rval;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  int __pyx_6;
  static char *__pyx_argnames[] = {"string",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_string)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_string);
  __pyx_v_rval = Py_None; Py_INCREF(__pyx_v_rval);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":48 */
  __pyx_1 = PyString_AsStringAndSize(__pyx_v_string,((char (*(*)))(&__pyx_v_s_buf)),(&__pyx_v_s_len)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":50 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_s_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_n_i);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_3;
  __pyx_3 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":51 */
  __pyx_1 = PyObject_AsWriteBuffer(__pyx_v_rval,((void (*(*)))(&__pyx_v_t_buf)),(&__pyx_v_t_len)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":53 */
  for (__pyx_5 = 0; __pyx_5 < __pyx_v_s_len; ++__pyx_5) {
    __pyx_2 = PyInt_FromLong(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":54 */
    __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    __pyx_6 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    (__pyx_v_t_buf[__pyx_6]) = (((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->table[(__pyx_v_s_buf[__pyx_1])]);
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":56 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.translate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_string);
  return __pyx_r;
}

static PyObject *__pyx_n_len;


static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate_list(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_21CharToIntArrayMapping_translate_list[] = "Translate a list of strings into an int array";
static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate_list(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_strings = 0;
  int __pyx_v_text_len;
  int __pyx_v_factor;
  int __pyx_v_i;
  int __pyx_v_s_len;
  int __pyx_v_t_len;
  unsigned char (*__pyx_v_s_buf);
  int (*__pyx_v_t_buf);
  PyObject *__pyx_v_rval;
  PyObject *__pyx_v_string;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {"strings",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_strings)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_strings);
  __pyx_v_rval = Py_None; Py_INCREF(__pyx_v_rval);
  __pyx_v_string = Py_None; Py_INCREF(__pyx_v_string);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":66 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  Py_INCREF(__pyx_v_strings);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_strings);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_3, __pyx_1, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_4 = __pyx_4 < 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_4) {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":69 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_1 = PyObject_GetItem(__pyx_v_strings, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_text_len = __pyx_4;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":72 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_text_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_n_i);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_3;
  __pyx_3 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":73 */
  __pyx_4 = PyObject_AsWriteBuffer(__pyx_v_rval,((void (*(*)))(&__pyx_v_t_buf)),(&__pyx_v_t_len)); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":76 */
  __pyx_v_factor = 1;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":77 */
  __pyx_2 = PyObject_GetIter(__pyx_v_strings); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  for (;;) {
    __pyx_L3:;
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_string);
    __pyx_v_string = __pyx_1;
    __pyx_1 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":78 */
    __pyx_4 = PyString_AsStringAndSize(__pyx_v_string,((char (*(*)))(&__pyx_v_s_buf)),(&__pyx_v_s_len)); if (__pyx_4 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":79 */
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_text_len; ++__pyx_v_i) {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":80 */
      __pyx_4 = ((__pyx_v_t_buf[__pyx_v_i]) >= 0);
      if (__pyx_4) {

        /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":81 */
        __pyx_4 = ((((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->table[(__pyx_v_s_buf[__pyx_v_i])]) == (-1));
        if (__pyx_4) {

          /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":82 */
          (__pyx_v_t_buf[__pyx_v_i]) = (-1);
          goto __pyx_L8;
        }
        /*else*/ {

          /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":84 */
          (__pyx_v_t_buf[__pyx_v_i]) = ((__pyx_v_t_buf[__pyx_v_i]) + ((((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->table[(__pyx_v_s_buf[__pyx_v_i])]) * __pyx_v_factor));
        }
        __pyx_L8:;
        goto __pyx_L7;
      }
      __pyx_L7:;
      __pyx_L5:;
    }
    __pyx_L6:;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":85 */
    __pyx_v_factor = (__pyx_v_factor * ((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size);
  }
  __pyx_L4:;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":86 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.translate_list");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_string);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_strings);
  return __pyx_r;
}

static PyObject *__pyx_n_append;
static PyObject *__pyx_n_int;
static PyObject *__pyx_n_reverse;

static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_reverse_map(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_reverse_map(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_val = 0;
  PyObject *__pyx_v_nseqs = 0;
  PyObject *__pyx_v_factor;
  PyObject *__pyx_v_rval;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"val","nseqs",0};
  extern double pow(double, double);
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_val, &__pyx_v_nseqs)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_val);
  Py_INCREF(__pyx_v_nseqs);
  __pyx_v_factor = Py_None; Py_INCREF(__pyx_v_factor);
  __pyx_v_rval = Py_None; Py_INCREF(__pyx_v_rval);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":89 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_3 = PyNumber_Subtract(__pyx_v_nseqs, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyNumber_Power(__pyx_1, __pyx_3, Py_None); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_factor);
  __pyx_v_factor = __pyx_2;
  __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":90 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_1;
  __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":91 */
  while (1) {
    __pyx_L2:;
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_factor, __pyx_3, &__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
    __pyx_4 = __pyx_4 > 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (!__pyx_4) break;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":92 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_rval, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_floor); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_5 = PyNumber_Divide(__pyx_v_val, __pyx_v_factor); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_6 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_5 = PyObject_GetItem(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->reverse_table, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":93 */
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_floor); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    __pyx_5 = PyNumber_Divide(__pyx_v_val, __pyx_v_factor); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_6, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyNumber_Multiply(__pyx_1, __pyx_v_factor); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_5 = PyNumber_Subtract(__pyx_v_val, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_val);
    __pyx_v_val = __pyx_5;
    __pyx_5 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":94 */
    __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_floor); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    __pyx_1 = PyNumber_Divide(__pyx_v_factor, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_6, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_factor);
    __pyx_v_factor = __pyx_5;
    __pyx_5 = 0;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":95 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_rval, __pyx_n_reverse); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_6 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":96 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.reverse_map");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_factor);
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_val);
  Py_DECREF(__pyx_v_nseqs);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_get_out_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_21CharToIntArrayMapping_get_out_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":99 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)__pyx_v_self)->out_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_seqmapping.CharToIntArrayMapping.get_out_size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k9p;

static char (__pyx_k9[]) = "Malloc Failed";

static int __pyx_f_11_seqmapping_15IntToIntMapping___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_11_seqmapping_15IntToIntMapping___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_in_size;
  PyObject *__pyx_v_i;
  int __pyx_r;
  int __pyx_1;
  long __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"in_size",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_in_size)) return -1;
  Py_INCREF(__pyx_v_self);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":108 */
  ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size = __pyx_v_in_size;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":109 */
  ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table = ((int (*))malloc((__pyx_v_in_size * (sizeof(int )))));

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":110 */
  __pyx_1 = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table == 0);
  if (__pyx_1) {
    __Pyx_Raise(__pyx_k9p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":111 */
  for (__pyx_2 = 0; __pyx_2 < __pyx_v_in_size; ++__pyx_2) {
    __pyx_3 = PyInt_FromLong(__pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_3;
    __pyx_3 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_1]) = (-1);
    __pyx_L3:;
  }
  __pyx_L4:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":112 */
  ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_11_seqmapping_15IntToIntMapping___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_11_seqmapping_15IntToIntMapping___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":116 */
  free(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table);

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_k10p;

static char (__pyx_k10[]) = "%d not between 0 and %s";

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_set_mapping(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_set_mapping(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_index;
  int __pyx_v_symbol;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"index","symbol",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ii", __pyx_argnames, &__pyx_v_index, &__pyx_v_symbol)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":119 */
  __pyx_1 = (-1) <= __pyx_v_index;
  if (__pyx_1) {
    __pyx_1 = __pyx_v_index < ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  }
  __pyx_2 = PyInt_FromLong(__pyx_v_index); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_k10p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__pyx_1) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_2);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":120 */
  (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_index]) = __pyx_v_symbol;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":121 */
  __pyx_1 = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size <= __pyx_v_symbol);
  if (__pyx_1) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":122 */
    ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size = (__pyx_v_symbol + 1);
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.set_mapping");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k11p;

static char (__pyx_k11[]) = "`src` argument must be a buffer of 32bit integers";

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_15IntToIntMapping_translate[] = "Translate `string` and return as int array";
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_translate(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_src = 0;
  int __pyx_v_s_len;
  int __pyx_v_t_len;
  int (*__pyx_v_s_buf);
  int (*__pyx_v_t_buf);
  PyObject *__pyx_v_rval;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  long __pyx_6;
  int __pyx_7;
  static char *__pyx_argnames[] = {"src",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_src)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_src);
  __pyx_v_rval = Py_None; Py_INCREF(__pyx_v_rval);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":129 */
  __pyx_1 = PyObject_AsReadBuffer(__pyx_v_src,((void (*(*)))(&__pyx_v_s_buf)),(&__pyx_v_s_len)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":130 */
  __pyx_v_s_len = (__pyx_v_s_len / (sizeof(int )));

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":131 */
  __pyx_2 = PyInt_FromLong(__pyx_v_s_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_INCREF(__pyx_v_src);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_src);
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyObject_Cmp(__pyx_2, __pyx_5, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (!__pyx_1) {
    PyErr_SetObject(PyExc_AssertionError, __pyx_k11p);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  }

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":133 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(__pyx_v_s_len); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_n_i);
  __pyx_4 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_5;
  __pyx_5 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":134 */
  __pyx_1 = PyObject_AsWriteBuffer(__pyx_v_rval,((void (*(*)))(&__pyx_v_t_buf)),(&__pyx_v_t_len)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":136 */
  for (__pyx_6 = 0; __pyx_6 < __pyx_v_s_len; ++__pyx_6) {
    __pyx_4 = PyInt_FromLong(__pyx_6); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_4;
    __pyx_4 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":137 */
    __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
    __pyx_7 = ((__pyx_v_s_buf[__pyx_1]) == (-1));
    if (__pyx_7) {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":138 */
      __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
      (__pyx_v_t_buf[__pyx_1]) = (-1);
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":140 */
      __pyx_7 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
      __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
      (__pyx_v_t_buf[__pyx_1]) = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[(__pyx_v_s_buf[__pyx_7])]);
    }
    __pyx_L4:;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":142 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.translate");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_src);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_x); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_x) {
  int __pyx_v_x;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_x = PyInt_AsLong(__pyx_arg_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":145 */
  __pyx_1 = (__pyx_v_x == (-1));
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong((-1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":146 */
  __pyx_1 = 0 <= __pyx_v_x;
  if (__pyx_1) {
    __pyx_1 = __pyx_v_x < ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  }
  if (!__pyx_1) {
    PyErr_SetNone(PyExc_AssertionError);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  }

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":147 */
  __pyx_2 = PyInt_FromLong((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_x])); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_collapse(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_collapse(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_a;
  int __pyx_v_b;
  int __pyx_v_i;
  struct __pyx_obj_11_seqmapping_IntToIntMapping *__pyx_v_copy;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"a","b",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ii", __pyx_argnames, &__pyx_v_a, &__pyx_v_b)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_copy = Py_None; Py_INCREF((PyObject *) __pyx_v_copy);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":152 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_11_seqmapping_IntToIntMapping), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (!__Pyx_TypeTest(__pyx_1, __pyx_ptype_11_seqmapping_IntToIntMapping)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_copy));
  __pyx_v_copy = __pyx_1;
  __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":153 */
  __pyx_v_copy->out_size = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size - 1);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":154 */
  __pyx_3 = (__pyx_v_a > __pyx_v_b);
  if (__pyx_3) {
    __pyx_3 = __pyx_v_b;
    __pyx_4 = __pyx_v_a;
    __pyx_v_a = __pyx_3;
    __pyx_v_b = __pyx_4;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":155 */
  __pyx_3 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_3; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":156 */
    __pyx_4 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_b);
    if (__pyx_4) {
      (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_a;
      goto __pyx_L5;
    }
    __pyx_4 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_copy->out_size);
    if (__pyx_4) {
      (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_b;
      goto __pyx_L5;
    }
    /*else*/ {
      (__pyx_v_copy->table[__pyx_v_i]) = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]);
    }
    __pyx_L5:;
    __pyx_L3:;
  }
  __pyx_L4:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":159 */
  Py_INCREF(((PyObject *)__pyx_v_copy));
  __pyx_r = ((PyObject *)__pyx_v_copy);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.collapse");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_copy);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_15IntToIntMapping_expand[] = "Grow the alphabet by making \'a\' a seperate symbol. If it already mapped to a single symbol, do nothing";
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_x;
  int __pyx_v_i;
  int __pyx_v_count;
  int __pyx_v_a;
  int __pyx_v_b;
  struct __pyx_obj_11_seqmapping_IntToIntMapping *__pyx_v_copy;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_copy = Py_None; Py_INCREF((PyObject *) __pyx_v_copy);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":166 */
  __pyx_v_a = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_x]);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":168 */
  __pyx_1 = (__pyx_v_a < 0);
  if (__pyx_1) {
    Py_INCREF(__pyx_v_self);
    __pyx_r = __pyx_v_self;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":170 */
  __pyx_v_count = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":171 */
  __pyx_1 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":172 */
    __pyx_2 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_a);
    if (__pyx_2) {
      __pyx_v_count = (__pyx_v_count + 1);
      goto __pyx_L5;
    }
    __pyx_L5:;
    __pyx_L3:;
  }
  __pyx_L4:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":174 */
  __pyx_2 = (__pyx_v_count < 2);
  if (__pyx_2) {
    Py_INCREF(__pyx_v_self);
    __pyx_r = __pyx_v_self;
    goto __pyx_L0;
    goto __pyx_L6;
  }
  __pyx_L6:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":176 */
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_11_seqmapping_IntToIntMapping), __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_11_seqmapping_IntToIntMapping)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_copy));
  __pyx_v_copy = __pyx_3;
  __pyx_3 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":177 */
  __pyx_v_copy->out_size = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size + 1);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":178 */
  __pyx_1 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":179 */
    (__pyx_v_copy->table[__pyx_v_i]) = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]);
    __pyx_L7:;
  }
  __pyx_L8:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":180 */
  (__pyx_v_copy->table[__pyx_v_x]) = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":181 */
  Py_INCREF(((PyObject *)__pyx_v_copy));
  __pyx_r = ((PyObject *)__pyx_v_copy);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.expand");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_copy);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_randrange;

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand_out(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_15IntToIntMapping_expand_out[] = "Grow the alphabet breaking \'a\' into two symbols randomly";
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand_out(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_a;
  int __pyx_v_i;
  int __pyx_v_count;
  int __pyx_v_to_split;
  int __pyx_v_b;
  struct __pyx_obj_11_seqmapping_IntToIntMapping *__pyx_v_copy;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"a",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_a)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_copy = Py_None; Py_INCREF((PyObject *) __pyx_v_copy);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":187 */
  __pyx_v_count = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":188 */
  __pyx_1 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":189 */
    __pyx_2 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_a);
    if (__pyx_2) {
      __pyx_v_count = (__pyx_v_count + 1);
      goto __pyx_L4;
    }
    __pyx_L4:;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":190 */
  __pyx_2 = (__pyx_v_count < 2);
  if (__pyx_2) {
    Py_INCREF(__pyx_v_self);
    __pyx_r = __pyx_v_self;
    goto __pyx_L0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":191 */
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_11_seqmapping_IntToIntMapping), __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_11_seqmapping_IntToIntMapping)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 191; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_copy));
  __pyx_v_copy = __pyx_3;
  __pyx_3 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":192 */
  __pyx_v_copy->out_size = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size + 1);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":193 */
  __pyx_v_b = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":194 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_random); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_randrange); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyInt_FromLong(__pyx_v_count); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 194; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_v_to_split = __pyx_1;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":195 */
  __pyx_v_count = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":196 */
  __pyx_2 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_2; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":197 */
    __pyx_1 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_a);
    if (__pyx_1) {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":198 */
      __pyx_1 = (__pyx_v_count == __pyx_v_to_split);
      if (__pyx_1) {
        (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_b;
        goto __pyx_L9;
      }
      /*else*/ {
        (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_a;
      }
      __pyx_L9:;

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":200 */
      __pyx_v_count = (__pyx_v_count + 1);
      goto __pyx_L8;
    }
    /*else*/ {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":202 */
      (__pyx_v_copy->table[__pyx_v_i]) = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]);
    }
    __pyx_L8:;
    __pyx_L6:;
  }
  __pyx_L7:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":203 */
  Py_INCREF(((PyObject *)__pyx_v_copy));
  __pyx_r = ((PyObject *)__pyx_v_copy);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.expand_out");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_copy);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_sample;
static PyObject *__pyx_n_range;

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand_random_split(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_11_seqmapping_15IntToIntMapping_expand_random_split[] = "Grow the alphabet breaking \'a\' into two symbols randomly";
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_expand_random_split(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_a;
  int __pyx_v_i;
  int __pyx_v_count;
  int __pyx_v_b;
  struct __pyx_obj_11_seqmapping_IntToIntMapping *__pyx_v_copy;
  PyObject *__pyx_v_to_split;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"a",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_a)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_copy = Py_None; Py_INCREF((PyObject *) __pyx_v_copy);
  __pyx_v_to_split = Py_None; Py_INCREF(__pyx_v_to_split);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":209 */
  __pyx_v_count = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":210 */
  __pyx_1 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":211 */
    __pyx_2 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_a);
    if (__pyx_2) {
      __pyx_v_count = (__pyx_v_count + 1);
      goto __pyx_L4;
    }
    __pyx_L4:;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":212 */
  __pyx_2 = (__pyx_v_count < 2);
  if (__pyx_2) {
    Py_INCREF(__pyx_v_self);
    __pyx_r = __pyx_v_self;
    goto __pyx_L0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":213 */
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(((PyObject*)__pyx_ptype_11_seqmapping_IntToIntMapping), __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (!__Pyx_TypeTest(__pyx_3, __pyx_ptype_11_seqmapping_IntToIntMapping)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_copy));
  __pyx_v_copy = __pyx_3;
  __pyx_3 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":214 */
  __pyx_v_copy->out_size = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size + 1);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":215 */
  __pyx_v_b = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":216 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_random); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_4, __pyx_n_sample); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_count); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_4 = PyInt_FromLong((__pyx_v_count / 2)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
  __pyx_5 = 0;
  __pyx_4 = 0;
  __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_v_to_split);
  __pyx_v_to_split = __pyx_5;
  __pyx_5 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":217 */
  __pyx_v_count = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":218 */
  __pyx_1 = ((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":219 */
    __pyx_2 = ((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]) == __pyx_v_a);
    if (__pyx_2) {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":220 */
      __pyx_4 = PyInt_FromLong(__pyx_v_count); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      __pyx_2 = PySequence_Contains(__pyx_v_to_split, __pyx_4); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 220; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      if (__pyx_2) {
        (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_b;
        goto __pyx_L9;
      }
      /*else*/ {
        (__pyx_v_copy->table[__pyx_v_i]) = __pyx_v_a;
      }
      __pyx_L9:;

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":222 */
      __pyx_v_count = (__pyx_v_count + 1);
      goto __pyx_L8;
    }
    /*else*/ {

      /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":224 */
      (__pyx_v_copy->table[__pyx_v_i]) = (((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_v_i]);
    }
    __pyx_L8:;
    __pyx_L6:;
  }
  __pyx_L7:;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":225 */
  Py_INCREF(((PyObject *)__pyx_v_copy));
  __pyx_r = ((PyObject *)__pyx_v_copy);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.expand_random_split");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_copy);
  Py_DECREF(__pyx_v_to_split);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_in_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_in_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":228 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 228; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.get_in_size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_out_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_out_size(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":231 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->out_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 231; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.get_out_size");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_table(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_11_seqmapping_15IntToIntMapping_get_table(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_rval;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_rval = Py_None; Py_INCREF(__pyx_v_rval);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":234 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  Py_INCREF(__pyx_n_i);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_n_i);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 234; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_rval);
  __pyx_v_rval = __pyx_2;
  __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":235 */
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->in_size); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyObject_GetIter(__pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_L2:;
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 235; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;

    /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":236 */
    __pyx_4 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong((((struct __pyx_obj_11_seqmapping_IntToIntMapping *)__pyx_v_self)->table[__pyx_4])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_rval, __pyx_v_i, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 236; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  __pyx_L3:;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":237 */
  Py_INCREF(__pyx_v_rval);
  __pyx_r = __pyx_v_rval;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("_seqmapping.IntToIntMapping.get_table");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_rval);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_Numeric, "Numeric"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_chr, "chr"},
  {&__pyx_n_dict, "dict"},
  {&__pyx_n_floor, "floor"},
  {&__pyx_n_i, "i"},
  {&__pyx_n_int, "int"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_math, "math"},
  {&__pyx_n_random, "random"},
  {&__pyx_n_randrange, "randrange"},
  {&__pyx_n_range, "range"},
  {&__pyx_n_reverse, "reverse"},
  {&__pyx_n_sample, "sample"},
  {&__pyx_n_sys, "sys"},
  {&__pyx_n_zeros, "zeros"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_k10p, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_k11p, __pyx_k11, sizeof(__pyx_k11)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_11_seqmapping_CharToIntArrayMapping(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *p = (struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)o;
  p->reverse_table = Py_None; Py_INCREF(p->reverse_table);
  if (__pyx_f_11_seqmapping_21CharToIntArrayMapping___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_11_seqmapping_CharToIntArrayMapping(PyObject *o) {
  struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *p = (struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)o;
  Py_XDECREF(p->reverse_table);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_11_seqmapping_CharToIntArrayMapping(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *p = (struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)o;
  if (p->reverse_table) {
    e = (*v)(p->reverse_table, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_11_seqmapping_CharToIntArrayMapping(PyObject *o) {
  struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *p = (struct __pyx_obj_11_seqmapping_CharToIntArrayMapping *)o;
  Py_XDECREF(p->reverse_table);
  p->reverse_table = Py_None; Py_INCREF(p->reverse_table);
  return 0;
}

static struct PyMethodDef __pyx_methods_11_seqmapping_CharToIntArrayMapping[] = {
  {"set_mapping", (PyCFunction)__pyx_f_11_seqmapping_21CharToIntArrayMapping_set_mapping, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_21CharToIntArrayMapping_set_mapping},
  {"translate", (PyCFunction)__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_21CharToIntArrayMapping_translate},
  {"translate_list", (PyCFunction)__pyx_f_11_seqmapping_21CharToIntArrayMapping_translate_list, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_21CharToIntArrayMapping_translate_list},
  {"reverse_map", (PyCFunction)__pyx_f_11_seqmapping_21CharToIntArrayMapping_reverse_map, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_out_size", (PyCFunction)__pyx_f_11_seqmapping_21CharToIntArrayMapping_get_out_size, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_CharToIntArrayMapping = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_CharToIntArrayMapping = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_CharToIntArrayMapping = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_CharToIntArrayMapping = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_11_seqmapping_CharToIntArrayMapping = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_seqmapping.CharToIntArrayMapping", /*tp_name*/
  sizeof(struct __pyx_obj_11_seqmapping_CharToIntArrayMapping), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_11_seqmapping_CharToIntArrayMapping, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_CharToIntArrayMapping, /*tp_as_number*/
  &__pyx_tp_as_sequence_CharToIntArrayMapping, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_CharToIntArrayMapping, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_CharToIntArrayMapping, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "Mapping for converting strings to int arrays", /*tp_doc*/
  __pyx_tp_traverse_11_seqmapping_CharToIntArrayMapping, /*tp_traverse*/
  __pyx_tp_clear_11_seqmapping_CharToIntArrayMapping, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_11_seqmapping_CharToIntArrayMapping, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_11_seqmapping_21CharToIntArrayMapping___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_11_seqmapping_CharToIntArrayMapping, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_11_seqmapping_IntToIntMapping(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_11_seqmapping_IntToIntMapping *p = (struct __pyx_obj_11_seqmapping_IntToIntMapping *)o;
  if (__pyx_f_11_seqmapping_15IntToIntMapping___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_11_seqmapping_IntToIntMapping(PyObject *o) {
  struct __pyx_obj_11_seqmapping_IntToIntMapping *p = (struct __pyx_obj_11_seqmapping_IntToIntMapping *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_11_seqmapping_15IntToIntMapping___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_11_seqmapping_IntToIntMapping(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_11_seqmapping_IntToIntMapping *p = (struct __pyx_obj_11_seqmapping_IntToIntMapping *)o;
  return 0;
}

static int __pyx_tp_clear_11_seqmapping_IntToIntMapping(PyObject *o) {
  struct __pyx_obj_11_seqmapping_IntToIntMapping *p = (struct __pyx_obj_11_seqmapping_IntToIntMapping *)o;
  return 0;
}
static PyObject *__pyx_sq_item_11_seqmapping_IntToIntMapping(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static struct PyMethodDef __pyx_methods_11_seqmapping_IntToIntMapping[] = {
  {"set_mapping", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_set_mapping, METH_VARARGS|METH_KEYWORDS, 0},
  {"translate", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_translate, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_15IntToIntMapping_translate},
  {"collapse", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_collapse, METH_VARARGS|METH_KEYWORDS, 0},
  {"expand", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_expand, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_15IntToIntMapping_expand},
  {"expand_out", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_expand_out, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_15IntToIntMapping_expand_out},
  {"expand_random_split", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_expand_random_split, METH_VARARGS|METH_KEYWORDS, __pyx_doc_11_seqmapping_15IntToIntMapping_expand_random_split},
  {"get_in_size", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_get_in_size, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_out_size", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_get_out_size, METH_VARARGS|METH_KEYWORDS, 0},
  {"get_table", (PyCFunction)__pyx_f_11_seqmapping_15IntToIntMapping_get_table, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_IntToIntMapping = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_IntToIntMapping = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_11_seqmapping_IntToIntMapping, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_IntToIntMapping = {
  0, /*mp_length*/
  __pyx_f_11_seqmapping_15IntToIntMapping___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_IntToIntMapping = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_11_seqmapping_IntToIntMapping = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "_seqmapping.IntToIntMapping", /*tp_name*/
  sizeof(struct __pyx_obj_11_seqmapping_IntToIntMapping), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_11_seqmapping_IntToIntMapping, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_IntToIntMapping, /*tp_as_number*/
  &__pyx_tp_as_sequence_IntToIntMapping, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_IntToIntMapping, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_IntToIntMapping, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_11_seqmapping_IntToIntMapping, /*tp_traverse*/
  __pyx_tp_clear_11_seqmapping_IntToIntMapping, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_11_seqmapping_IntToIntMapping, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_11_seqmapping_IntToIntMapping, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) init_seqmapping(void); /*proto*/
DL_EXPORT(void) init_seqmapping(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_m = Py_InitModule4("_seqmapping", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_type_11_seqmapping_CharToIntArrayMapping.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_11_seqmapping_CharToIntArrayMapping) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "CharToIntArrayMapping", (PyObject *)&__pyx_type_11_seqmapping_CharToIntArrayMapping) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  __pyx_ptype_11_seqmapping_CharToIntArrayMapping = &__pyx_type_11_seqmapping_CharToIntArrayMapping;
  if (PyType_Ready(&__pyx_type_11_seqmapping_IntToIntMapping) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "IntToIntMapping", (PyObject *)&__pyx_type_11_seqmapping_IntToIntMapping) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_ptype_11_seqmapping_IntToIntMapping = &__pyx_type_11_seqmapping_IntToIntMapping;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":14 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_INCREF(__pyx_n_zeros);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_zeros);
  __pyx_2 = __Pyx_Import(__pyx_n_Numeric, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_zeros, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":15 */
  __pyx_2 = PyList_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_INCREF(__pyx_n_floor);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_floor);
  __pyx_1 = __Pyx_Import(__pyx_n_math, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_floor); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_floor, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":16 */
  __pyx_1 = __Pyx_Import(__pyx_n_random, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_random, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":17 */
  __pyx_2 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/afs/bx.psu.edu/home/greg/workspaces/galaxy/james_taylor_bx/trunk/lib/bx/_seqmapping.pyx":233 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("_seqmapping");
}

static char *__pyx_filenames[] = {
  "_seqmapping.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
