/* Generated by Pyrex 0.9.3.1 on Tue Mar  7 14:04:22 2006 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "common.h"
#include "bits.h"
#include "binBits.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from bitset */

staticforward PyTypeObject __pyx_type_6bitset_BitSet;

struct __pyx_obj_6bitset_BitSet {
  PyObject_HEAD
  Bits (*bits);
  int bitCount;
};

staticforward PyTypeObject __pyx_type_6bitset_BinnedBitSet;

struct __pyx_obj_6bitset_BinnedBitSet {
  PyObject_HEAD
  struct BinBits (*bb);
};

static PyTypeObject *__pyx_ptype_6bitset_BitSet = 0;
static PyTypeObject *__pyx_ptype_6bitset_BinnedBitSet = 0;
static PyObject *__pyx_k1;
static PyObject *__pyx_k2;
static PyObject *__pyx_k3;
static PyObject *__pyx_k4;
static int __pyx_k5;
static int __pyx_k6;

/* Implementation of bitset */

static PyObject *__pyx_n_MAX;

static int __pyx_f_6bitset_6BitSet___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6bitset_6BitSet___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_bitCount;
  int __pyx_r;
  static char *__pyx_argnames[] = {"bitCount",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_bitCount)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":64 */
  ((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount = __pyx_v_bitCount;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":65 */
  ((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits = bitAlloc(__pyx_v_bitCount);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_6bitset_6BitSet___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_6bitset_6BitSet___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":68 */
  bitFree((&((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits));

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_6bitset_6BitSet_4size___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_4size___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":77 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bitset.BitSet.size.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_index = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"index",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_index)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":80 */
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  bitSetOne(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_index = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"index",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_index)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":83 */
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  bitClearOne(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.clear");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static PyObject *__pyx_n_ior;

static PyObject *__pyx_f_6bitset_6BitSet_clone(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_clone(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_other;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_other = Py_None; Py_INCREF(__pyx_v_other);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":86 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject*)__pyx_ptype_6bitset_BitSet), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_other);
  __pyx_v_other = __pyx_1;
  __pyx_1 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":87 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_other, __pyx_n_ior); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_self);
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":88 */
  Py_INCREF(__pyx_v_other);
  __pyx_r = __pyx_v_other;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BitSet.clone");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_other);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_set_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_set_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_v_count = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {"start","count",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_start, &__pyx_v_count)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);
  Py_INCREF(__pyx_v_count);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":91 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_count); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  bitSetRange(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1,__pyx_2);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.set_range");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  Py_DECREF(__pyx_v_count);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_index = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"index",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_index)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":94 */
  __pyx_1 = PyInt_AsLong(__pyx_v_index); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(bitReadOne(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BitSet.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_count_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_count_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_v_count = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"start","count",0};
  __pyx_v_start = __pyx_k1;
  __pyx_v_count = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OO", __pyx_argnames, &__pyx_v_start, &__pyx_v_count)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);
  Py_INCREF(__pyx_v_count);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":97 */
  if (PyObject_Cmp(__pyx_v_count, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
    Py_DECREF(__pyx_v_count);
    __pyx_v_count = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":98 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_count); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(bitCountRange(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1,__pyx_3)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BitSet.count_range");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  Py_DECREF(__pyx_v_count);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_next_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_next_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_v_end = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"start","end",0};
  __pyx_v_end = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_start, &__pyx_v_end)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);
  Py_INCREF(__pyx_v_end);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":101 */
  if (PyObject_Cmp(__pyx_v_end, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    Py_DECREF(__pyx_v_end);
    __pyx_v_end = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":102 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_end); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(bitFindSet(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1,__pyx_3)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BitSet.next_set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  Py_DECREF(__pyx_v_end);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_next_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_next_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_v_end = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"start","end",0};
  __pyx_v_end = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_start, &__pyx_v_end)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);
  Py_INCREF(__pyx_v_end);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":105 */
  if (PyObject_Cmp(__pyx_v_end, Py_None, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_DECREF(__pyx_v_end);
    __pyx_v_end = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":106 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_end); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(bitFindClear(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_1,__pyx_3)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BitSet.next_clear");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  Py_DECREF(__pyx_v_end);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_iand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_iand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6bitset_BitSet *__pyx_v_other = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_6bitset_BitSet, 1, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":109 */
  bitAnd(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_v_other->bits,((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.iand");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_ior(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_ior(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6bitset_BitSet *__pyx_v_other = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_6bitset_BitSet, 1, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":112 */
  bitOr(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_v_other->bits,((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.ior");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_ixor(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_ixor(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6bitset_BitSet *__pyx_v_other = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_6bitset_BitSet, 1, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":115 */
  bitXor(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,__pyx_v_other->bits,((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.ixor");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet_invert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet_invert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":118 */
  bitNot(((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bits,((struct __pyx_obj_6bitset_BitSet *)__pyx_v_self)->bitCount);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BitSet.invert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_get;

static PyObject *__pyx_f_6bitset_6BitSet___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_index) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_index);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":123 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_get); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_INCREF(__pyx_v_index);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_index);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BitSet.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_index);
  return __pyx_r;
}

static PyObject *__pyx_n_iand;

static PyObject *__pyx_f_6bitset_6BitSet___iand__(PyObject *__pyx_v_self, PyObject *__pyx_v_other); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet___iand__(PyObject *__pyx_v_self, PyObject *__pyx_v_other) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":126 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_iand); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_INCREF(__pyx_v_other);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_other);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":127 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BitSet.__iand__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_6BitSet___ior__(PyObject *__pyx_v_self, PyObject *__pyx_v_other); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet___ior__(PyObject *__pyx_v_self, PyObject *__pyx_v_other) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":130 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_ior); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_INCREF(__pyx_v_other);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_other);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 130; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":131 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BitSet.__ior__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_n_invert;

static PyObject *__pyx_f_6bitset_6BitSet___invert__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6bitset_6BitSet___invert__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":134 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_invert); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":135 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BitSet.__invert__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_6bitset_12BinnedBitSet___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6bitset_12BinnedBitSet___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_size;
  int __pyx_v_granularity;
  int __pyx_r;
  static char *__pyx_argnames[] = {"size","granularity",0};
  __pyx_v_size = __pyx_k5;
  __pyx_v_granularity = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|ii", __pyx_argnames, &__pyx_v_size, &__pyx_v_granularity)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":142 */
  ((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb = binBitsAlloc(__pyx_v_size,__pyx_v_granularity);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet___dealloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet___dealloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":144 */
  binBitsFree(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.__dealloc");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_pos); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_v_pos) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":146 */
  __pyx_1 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(binBitsReadOne(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BinnedBitSet.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":148 */
  __pyx_1 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  binBitsSetOne(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_pos = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"pos",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_pos)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_pos);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":150 */
  __pyx_1 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  binBitsClearOne(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.clear");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_pos);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_set_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_set_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_start;
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"start","size",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "iO", __pyx_argnames, &__pyx_v_start, &__pyx_v_size)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_size);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":152 */
  __pyx_1 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  binBitsSetRange(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_v_start,__pyx_1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.set_range");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_size);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_count_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_count_range(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_v_size = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"start","size",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_start, &__pyx_v_size)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);
  Py_INCREF(__pyx_v_size);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":154 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(binBitsCountRange(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1,__pyx_2)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("bitset.BinnedBitSet.count_range");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  Py_DECREF(__pyx_v_size);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_next_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_next_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"start",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_start)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":156 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(binBitsFindSet(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 156; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BinnedBitSet.next_set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_next_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_next_clear(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_start = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"start",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_start)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_start);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":158 */
  __pyx_1 = PyInt_AsLong(__pyx_v_start); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(binBitsFindClear(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 158; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset.BinnedBitSet.next_clear");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_start);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_4size___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_4size___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":161 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb->size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bitset.BinnedBitSet.size.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_8bin_size___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_8bin_size___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":164 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb->bin_size); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bitset.BinnedBitSet.bin_size.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_iand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_iand(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6bitset_BinnedBitSet *__pyx_v_other = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_6bitset_BinnedBitSet, 1, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 165; goto __pyx_L1;}

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":166 */
  binBitsAnd(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_v_other->bb);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.iand");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_ior(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_ior(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_6bitset_BinnedBitSet *__pyx_v_other = 0;
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {"other",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_other)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_other);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_other), __pyx_ptype_6bitset_BinnedBitSet, 1, "other")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":168 */
  binBitsOr(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb,__pyx_v_other->bb);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.ior");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_other);
  return __pyx_r;
}

static PyObject *__pyx_f_6bitset_12BinnedBitSet_invert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6bitset_12BinnedBitSet_invert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":170 */
  binBitsNot(((struct __pyx_obj_6bitset_BinnedBitSet *)__pyx_v_self)->bb);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitset.BinnedBitSet.invert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_MAX, "MAX"},
  {&__pyx_n_get, "get"},
  {&__pyx_n_iand, "iand"},
  {&__pyx_n_invert, "invert"},
  {&__pyx_n_ior, "ior"},
  {0, 0}
};

static PyObject *__pyx_tp_new_6bitset_BitSet(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_6bitset_BitSet *p = (struct __pyx_obj_6bitset_BitSet *)o;
  if (__pyx_f_6bitset_6BitSet___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_6bitset_BitSet(PyObject *o) {
  struct __pyx_obj_6bitset_BitSet *p = (struct __pyx_obj_6bitset_BitSet *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_6bitset_6BitSet___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_6bitset_BitSet(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_6bitset_BitSet *p = (struct __pyx_obj_6bitset_BitSet *)o;
  return 0;
}

static int __pyx_tp_clear_6bitset_BitSet(PyObject *o) {
  struct __pyx_obj_6bitset_BitSet *p = (struct __pyx_obj_6bitset_BitSet *)o;
  return 0;
}
static PyObject *__pyx_sq_item_6bitset_BitSet(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static PyObject *__pyx_getprop_6bitset_6BitSet_size(PyObject *o, void *x) {
  return __pyx_f_6bitset_6BitSet_4size___get__(o);
}

static struct PyMethodDef __pyx_methods_6bitset_BitSet[] = {
  {"set", (PyCFunction)__pyx_f_6bitset_6BitSet_set, METH_VARARGS|METH_KEYWORDS, 0},
  {"clear", (PyCFunction)__pyx_f_6bitset_6BitSet_clear, METH_VARARGS|METH_KEYWORDS, 0},
  {"clone", (PyCFunction)__pyx_f_6bitset_6BitSet_clone, METH_VARARGS|METH_KEYWORDS, 0},
  {"set_range", (PyCFunction)__pyx_f_6bitset_6BitSet_set_range, METH_VARARGS|METH_KEYWORDS, 0},
  {"get", (PyCFunction)__pyx_f_6bitset_6BitSet_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"count_range", (PyCFunction)__pyx_f_6bitset_6BitSet_count_range, METH_VARARGS|METH_KEYWORDS, 0},
  {"next_set", (PyCFunction)__pyx_f_6bitset_6BitSet_next_set, METH_VARARGS|METH_KEYWORDS, 0},
  {"next_clear", (PyCFunction)__pyx_f_6bitset_6BitSet_next_clear, METH_VARARGS|METH_KEYWORDS, 0},
  {"iand", (PyCFunction)__pyx_f_6bitset_6BitSet_iand, METH_VARARGS|METH_KEYWORDS, 0},
  {"ior", (PyCFunction)__pyx_f_6bitset_6BitSet_ior, METH_VARARGS|METH_KEYWORDS, 0},
  {"ixor", (PyCFunction)__pyx_f_6bitset_6BitSet_ixor, METH_VARARGS|METH_KEYWORDS, 0},
  {"invert", (PyCFunction)__pyx_f_6bitset_6BitSet_invert, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyGetSetDef __pyx_getsets_6bitset_BitSet[] = {
  {"size", __pyx_getprop_6bitset_6BitSet_size, 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BitSet = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  __pyx_f_6bitset_6BitSet___invert__, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  __pyx_f_6bitset_6BitSet___iand__, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  __pyx_f_6bitset_6BitSet___ior__, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BitSet = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_6bitset_BitSet, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BitSet = {
  0, /*mp_length*/
  __pyx_f_6bitset_6BitSet___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BitSet = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_6bitset_BitSet = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "bitset.BitSet", /*tp_name*/
  sizeof(struct __pyx_obj_6bitset_BitSet), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6bitset_BitSet, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BitSet, /*tp_as_number*/
  &__pyx_tp_as_sequence_BitSet, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BitSet, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BitSet, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_6bitset_BitSet, /*tp_traverse*/
  __pyx_tp_clear_6bitset_BitSet, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6bitset_BitSet, /*tp_methods*/
  0, /*tp_members*/
  __pyx_getsets_6bitset_BitSet, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6bitset_BitSet, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_6bitset_BinnedBitSet(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_6bitset_BinnedBitSet *p = (struct __pyx_obj_6bitset_BinnedBitSet *)o;
  if (__pyx_f_6bitset_12BinnedBitSet___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_6bitset_BinnedBitSet(PyObject *o) {
  struct __pyx_obj_6bitset_BinnedBitSet *p = (struct __pyx_obj_6bitset_BinnedBitSet *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_6bitset_BinnedBitSet(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_6bitset_BinnedBitSet *p = (struct __pyx_obj_6bitset_BinnedBitSet *)o;
  return 0;
}

static int __pyx_tp_clear_6bitset_BinnedBitSet(PyObject *o) {
  struct __pyx_obj_6bitset_BinnedBitSet *p = (struct __pyx_obj_6bitset_BinnedBitSet *)o;
  return 0;
}
static PyObject *__pyx_sq_item_6bitset_BinnedBitSet(PyObject *o, int i) {
  PyObject *r;
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  r = o->ob_type->tp_as_mapping->mp_subscript(o, x);
  Py_DECREF(x);
  return r;
}

static PyObject *__pyx_getprop_6bitset_12BinnedBitSet_size(PyObject *o, void *x) {
  return __pyx_f_6bitset_12BinnedBitSet_4size___get__(o);
}

static PyObject *__pyx_getprop_6bitset_12BinnedBitSet_bin_size(PyObject *o, void *x) {
  return __pyx_f_6bitset_12BinnedBitSet_8bin_size___get__(o);
}

static struct PyMethodDef __pyx_methods_6bitset_BinnedBitSet[] = {
  {"__dealloc", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet___dealloc, METH_VARARGS|METH_KEYWORDS, 0},
  {"set", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_set, METH_VARARGS|METH_KEYWORDS, 0},
  {"clear", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_clear, METH_VARARGS|METH_KEYWORDS, 0},
  {"set_range", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_set_range, METH_VARARGS|METH_KEYWORDS, 0},
  {"count_range", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_count_range, METH_VARARGS|METH_KEYWORDS, 0},
  {"next_set", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_next_set, METH_VARARGS|METH_KEYWORDS, 0},
  {"next_clear", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_next_clear, METH_VARARGS|METH_KEYWORDS, 0},
  {"iand", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_iand, METH_VARARGS|METH_KEYWORDS, 0},
  {"ior", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_ior, METH_VARARGS|METH_KEYWORDS, 0},
  {"invert", (PyCFunction)__pyx_f_6bitset_12BinnedBitSet_invert, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyGetSetDef __pyx_getsets_6bitset_BinnedBitSet[] = {
  {"size", __pyx_getprop_6bitset_12BinnedBitSet_size, 0, 0, 0},
  {"bin_size", __pyx_getprop_6bitset_12BinnedBitSet_bin_size, 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BinnedBitSet = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BinnedBitSet = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_6bitset_BinnedBitSet, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BinnedBitSet = {
  0, /*mp_length*/
  __pyx_f_6bitset_12BinnedBitSet___getitem__, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BinnedBitSet = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_6bitset_BinnedBitSet = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "bitset.BinnedBitSet", /*tp_name*/
  sizeof(struct __pyx_obj_6bitset_BinnedBitSet), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6bitset_BinnedBitSet, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BinnedBitSet, /*tp_as_number*/
  &__pyx_tp_as_sequence_BinnedBitSet, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BinnedBitSet, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BinnedBitSet, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_6bitset_BinnedBitSet, /*tp_traverse*/
  __pyx_tp_clear_6bitset_BinnedBitSet, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6bitset_BinnedBitSet, /*tp_methods*/
  0, /*tp_members*/
  __pyx_getsets_6bitset_BinnedBitSet, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6bitset_BinnedBitSet, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initbitset(void); /*proto*/
DL_EXPORT(void) initbitset(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  __pyx_m = Py_InitModule4("bitset", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_6bitset_BitSet) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BitSet", (PyObject *)&__pyx_type_6bitset_BitSet) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
  __pyx_ptype_6bitset_BitSet = &__pyx_type_6bitset_BitSet;
  if (PyType_Ready(&__pyx_type_6bitset_BinnedBitSet) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BinnedBitSet", (PyObject *)&__pyx_type_6bitset_BinnedBitSet) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_ptype_6bitset_BinnedBitSet = &__pyx_type_6bitset_BinnedBitSet;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":96 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_k1 = __pyx_1;
  __pyx_1 = 0;
  Py_INCREF(Py_None);
  __pyx_k2 = Py_None;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":100 */
  Py_INCREF(Py_None);
  __pyx_k3 = Py_None;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":104 */
  Py_INCREF(Py_None);
  __pyx_k4 = Py_None;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":137 */
  __pyx_2 = PyInt_FromLong(((512 * 1024) * 1024)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MAX, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":141 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MAX); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_k5 = __pyx_3;
  __pyx_k6 = 1024;

  /* "/home/james/projects/bx-python-trunk/lib/bx/bitset.pyx":169 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("bitset");
}

static char *__pyx_filenames[] = {
  "bitset.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
