/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__bx__bbi__bbi_file
#define __PYX_HAVE__bx__bbi__bbi_file


#ifndef __PYX_HAVE_API__bx__bbi__bbi_file

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) big_wig_sig;
__PYX_EXTERN_C DL_IMPORT(int) big_bed_sig;

#endif /* !__PYX_HAVE_API__bx__bbi__bbi_file */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbbi_file(void);
#else
PyMODINIT_FUNC PyInit_bbi_file(void);
#endif

#endif /* !__PYX_HAVE__bx__bbi__bbi_file */
