/* Generated by Pyrex 0.9.3.1 on Fri Oct 19 20:19:04 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "common.h"
#include "cluster.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "\nClusterTree data structure that supports efficient queries for \"cluster\" of\nintervals (groups where no interval is more than some distance from at least\none other).\n\nTODO: Documentation of the algorithmic details.\n";

/* Declarations from cluster */

staticforward PyTypeObject __pyx_type_7cluster_ClusterTree;

struct __pyx_obj_7cluster_ClusterTree {
  PyObject_HEAD
  struct ClusterNode (*root);
  int mincols;
  int minregions;
};

static PyTypeObject *__pyx_ptype_7cluster_ClusterTree = 0;

/* Implementation of cluster */

static PyObject *__pyx_k1p;
static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;

static char (__pyx_k1[]) = "BX: DEBUG\n";
static char (__pyx_k2[]) = "In __new__\n";
static char (__pyx_k3[]) = "Values of mincols, minregions: %d\t%d\n";

static int __pyx_f_7cluster_11ClusterTree___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_7cluster_11ClusterTree___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_mincols = 0;
  PyObject *__pyx_v_minregions = 0;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"mincols","minregions",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_mincols, &__pyx_v_minregions)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_mincols);
  Py_INCREF(__pyx_v_minregions);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":53 */
  ((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root = 0;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":54 */
  __pyx_1 = PyInt_AsLong(__pyx_v_mincols); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  ((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->mincols = __pyx_1;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":55 */
  __pyx_1 = PyInt_AsLong(__pyx_v_minregions); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  ((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->minregions = __pyx_1;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":56 */
  if (__Pyx_PrintItem(__pyx_k1p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":57 */
  if (__Pyx_PrintItem(__pyx_k2p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":58 */
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->mincols); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->minregions); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_k3p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cluster.ClusterTree.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_mincols);
  Py_DECREF(__pyx_v_minregions);
  return __pyx_r;
}

static PyObject *__pyx_n_sys;
static PyObject *__pyx_n_stderr;
static PyObject *__pyx_n_write;
static PyObject *__pyx_n_flush;

static PyObject *__pyx_k4p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;

static char (__pyx_k4[]) = "In __dealloc__\n";
static char (__pyx_k5[]) = "From ClusterTree, cluster.pyx, freetree failed\n";
static char (__pyx_k6[]) = "From ClusterTree, cluster.pyx. freetree failed\n";

static void __pyx_f_7cluster_11ClusterTree___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_7cluster_11ClusterTree___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":62 */
  if (__Pyx_PrintItem(__pyx_k4p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":63 */
  __pyx_1 = (((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root == 0);
  if (__pyx_1) {

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":64 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_sys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_stderr); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_write); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_INCREF(__pyx_k5p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k5p);
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":64 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_sys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_stderr); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_flush); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":65 */
    __Pyx_Raise(__pyx_k6p, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":67 */
    freetree((&((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root));
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cluster.ClusterTree.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_k7p;

static char (__pyx_k7[]) = "In insert, values of start %d end %d linenum %d\n";

static PyObject *__pyx_f_7cluster_11ClusterTree_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7cluster_11ClusterTree_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_start;
  int __pyx_v_end;
  int __pyx_v_linenum;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"start","end","linenum",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "iii", __pyx_argnames, &__pyx_v_start, &__pyx_v_end, &__pyx_v_linenum)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":70 */
  __pyx_1 = PyInt_FromLong(__pyx_v_start); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_end); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_linenum); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k7p, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__Pyx_PrintItem(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":71 */
  clusterNodeInsert((&((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root),__pyx_v_start,__pyx_v_end,__pyx_v_linenum,((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->mincols);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":72 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cluster.ClusterTree.insert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_append;

static PyObject *__pyx_k8p;

static char (__pyx_k8[]) = "In getregions\n";

static PyObject *__pyx_f_7cluster_11ClusterTree_getregions(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7cluster_11ClusterTree_getregions(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct treeitr (*__pyx_v_myitr);
  struct ClusterNode (*__pyx_v_node);
  struct linelist (*__pyx_v_nums);
  struct listitem (*__pyx_v_num);
  PyObject *__pyx_v_regions;
  PyObject *__pyx_v_lines;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_regions = Py_None; Py_INCREF(__pyx_v_regions);
  __pyx_v_lines = Py_None; Py_INCREF(__pyx_v_lines);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":80 */
  if (__Pyx_PrintItem(__pyx_k8p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":81 */
  __pyx_v_myitr = 0;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":82 */
  get_itr_in(((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root,(&__pyx_v_myitr));

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":83 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_v_regions);
  __pyx_v_regions = __pyx_1;
  __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":84 */
  while (1) {
    __pyx_L2:;
    __pyx_2 = has_next((&__pyx_v_myitr));
    if (!__pyx_2) break;

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":85 */
    __pyx_v_node = next((&__pyx_v_myitr));

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":86 */
    __pyx_2 = (__pyx_v_node->regions >= ((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->minregions);
    if (__pyx_2) {

      /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":87 */
      __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
      Py_DECREF(__pyx_v_lines);
      __pyx_v_lines = __pyx_1;
      __pyx_1 = 0;

      /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":88 */
      __pyx_2 = (__pyx_v_node->linenums != 0);
      if (__pyx_2) {
        __pyx_2 = (__pyx_v_node->linenums->head != 0);
      }
      if (__pyx_2) {

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":89 */
        __pyx_v_nums = __pyx_v_node->linenums;

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":90 */
        __pyx_v_num = __pyx_v_nums->head;

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":91 */
        while (1) {
          __pyx_L6:;
          __pyx_2 = (__pyx_v_num != 0);
          if (!__pyx_2) break;

          /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":92 */
          __pyx_1 = PyObject_GetAttr(__pyx_v_lines, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
          __pyx_3 = PyInt_FromLong(__pyx_v_num->value); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
          __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
          PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
          __pyx_3 = 0;
          __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
          Py_DECREF(__pyx_1); __pyx_1 = 0;
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          Py_DECREF(__pyx_3); __pyx_3 = 0;

          /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":93 */
          __pyx_v_num = __pyx_v_num->next;
        }
        __pyx_L7:;
        goto __pyx_L5;
      }
      __pyx_L5:;

      /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":94 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_regions, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      __pyx_4 = PyInt_FromLong(__pyx_v_node->start); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(__pyx_v_node->end); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
      PyTuple_SET_ITEM(__pyx_5, 1, __pyx_3);
      Py_INCREF(__pyx_v_lines);
      PyTuple_SET_ITEM(__pyx_5, 2, __pyx_v_lines);
      __pyx_4 = 0;
      __pyx_3 = 0;
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_5);
      __pyx_5 = 0;
      __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L4;
    }
    __pyx_L4:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":96 */
  Py_INCREF(__pyx_v_regions);
  __pyx_r = __pyx_v_regions;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("cluster.ClusterTree.getregions");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_regions);
  Py_DECREF(__pyx_v_lines);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k9p;

static char (__pyx_k9[]) = "In getlines\n";

static PyObject *__pyx_f_7cluster_11ClusterTree_getlines(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_7cluster_11ClusterTree_getlines(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct treeitr (*__pyx_v_myitr);
  struct ClusterNode (*__pyx_v_node);
  struct linelist (*__pyx_v_nums);
  struct listitem (*__pyx_v_num);
  PyObject *__pyx_v_lines;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_lines = Py_None; Py_INCREF(__pyx_v_lines);

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":104 */
  if (__Pyx_PrintItem(__pyx_k9p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}
  if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; goto __pyx_L1;}

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":106 */
  __pyx_v_myitr = 0;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":107 */
  get_itr_in(((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->root,(&__pyx_v_myitr));

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":108 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
  Py_DECREF(__pyx_v_lines);
  __pyx_v_lines = __pyx_1;
  __pyx_1 = 0;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":109 */
  while (1) {
    __pyx_L2:;
    __pyx_2 = has_next((&__pyx_v_myitr));
    if (!__pyx_2) break;

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":110 */
    __pyx_v_node = next((&__pyx_v_myitr));

    /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":111 */
    __pyx_2 = (__pyx_v_node->regions >= ((struct __pyx_obj_7cluster_ClusterTree *)__pyx_v_self)->minregions);
    if (__pyx_2) {

      /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":112 */
      __pyx_2 = (__pyx_v_node->linenums != 0);
      if (__pyx_2) {
        __pyx_2 = (__pyx_v_node->linenums->head != 0);
      }
      if (__pyx_2) {

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":113 */
        __pyx_v_nums = __pyx_v_node->linenums;

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":114 */
        __pyx_v_num = __pyx_v_nums->head;

        /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":115 */
        while (1) {
          __pyx_L6:;
          __pyx_2 = (__pyx_v_num != 0);
          if (!__pyx_2) break;

          /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":116 */
          __pyx_1 = PyObject_GetAttr(__pyx_v_lines, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
          __pyx_3 = PyInt_FromLong(__pyx_v_num->value); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
          __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
          PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
          __pyx_3 = 0;
          __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
          Py_DECREF(__pyx_1); __pyx_1 = 0;
          Py_DECREF(__pyx_4); __pyx_4 = 0;
          Py_DECREF(__pyx_3); __pyx_3 = 0;

          /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":117 */
          __pyx_v_num = __pyx_v_num->next;
        }
        __pyx_L7:;
        goto __pyx_L5;
      }
      __pyx_L5:;
      goto __pyx_L4;
    }
    __pyx_L4:;
  }
  __pyx_L3:;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":118 */
  Py_INCREF(__pyx_v_lines);
  __pyx_r = __pyx_v_lines;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("cluster.ClusterTree.getlines");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_lines);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_append, "append"},
  {&__pyx_n_flush, "flush"},
  {&__pyx_n_stderr, "stderr"},
  {&__pyx_n_sys, "sys"},
  {&__pyx_n_write, "write"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, __pyx_k9, sizeof(__pyx_k9)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_7cluster_ClusterTree(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_7cluster_ClusterTree *p = (struct __pyx_obj_7cluster_ClusterTree *)o;
  if (__pyx_f_7cluster_11ClusterTree___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_7cluster_ClusterTree(PyObject *o) {
  struct __pyx_obj_7cluster_ClusterTree *p = (struct __pyx_obj_7cluster_ClusterTree *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_7cluster_11ClusterTree___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_7cluster_ClusterTree(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_7cluster_ClusterTree *p = (struct __pyx_obj_7cluster_ClusterTree *)o;
  return 0;
}

static int __pyx_tp_clear_7cluster_ClusterTree(PyObject *o) {
  struct __pyx_obj_7cluster_ClusterTree *p = (struct __pyx_obj_7cluster_ClusterTree *)o;
  return 0;
}

static struct PyMethodDef __pyx_methods_7cluster_ClusterTree[] = {
  {"insert", (PyCFunction)__pyx_f_7cluster_11ClusterTree_insert, METH_VARARGS|METH_KEYWORDS, 0},
  {"getregions", (PyCFunction)__pyx_f_7cluster_11ClusterTree_getregions, METH_VARARGS|METH_KEYWORDS, 0},
  {"getlines", (PyCFunction)__pyx_f_7cluster_11ClusterTree_getlines, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ClusterTree = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_ClusterTree = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ClusterTree = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ClusterTree = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_7cluster_ClusterTree = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "cluster.ClusterTree", /*tp_name*/
  sizeof(struct __pyx_obj_7cluster_ClusterTree), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_7cluster_ClusterTree, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ClusterTree, /*tp_as_number*/
  &__pyx_tp_as_sequence_ClusterTree, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ClusterTree, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ClusterTree, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_7cluster_ClusterTree, /*tp_traverse*/
  __pyx_tp_clear_7cluster_ClusterTree, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_7cluster_ClusterTree, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_7cluster_ClusterTree, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initcluster(void); /*proto*/
DL_EXPORT(void) initcluster(void) {
  __pyx_m = Py_InitModule4("cluster", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_7cluster_ClusterTree) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ClusterTree", (PyObject *)&__pyx_type_7cluster_ClusterTree) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_ptype_7cluster_ClusterTree = &__pyx_type_7cluster_ClusterTree;

  /* "/afs/bx.psu.edu/home/radhesh/bx_code/svnroot/trunk/lib/bx/intervals/cluster.pyx":98 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("cluster");
}

static char *__pyx_filenames[] = {
  "cluster.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        int len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
