name: Lint and test
on: [push, pull_request]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flake8
        run: pip install flake8 flake8-import-order
      - name: Lint
        run: flake8 .
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install liblzo2-dev
        run: sudo apt-get update && sudo apt-get -y install liblzo2-dev
      - name: Install tox
        run: pip install tox
      - name: Test
        run: tox
  test-32bit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      C_COMPILER: i686-linux-gnu-gcc
      CFLAGS: -m32
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install 32bit libraries
        run: sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install -y gcc-i686-linux-gnu python3.7:i386 python3.7-minimal:i386 python3.7-dev:i386 python3-pip liblzo2-dev:i386
      - name: Install tox
        run: export PYTHON=python3.7 && sudo -H $PYTHON -m pip install -U pip \
                  && sudo -H $PYTHON -m pip install wheel virtualenv setuptools tox
      - name: Test
        run: tox
